### PR TITLE
Possibility to make custom cache key generation strategy

### PR DESCRIPTION
**Pull request by dlukanin**
Hello!

We are using your library in production and it works great, so thank you very much.

But in some cases default cache key creating strategy is not great. JSON stringify can throw error on complex recursive objects. Also at the highload JSON.stringify can be a bottleneck and we need to use some alternatives (for example https://github.com/ibmruntimes/yieldable-json). 

So i made a possibility to bypass custom key generation strategy. Also added some interfaces, tests and added new possibility to docs.

### CODE REVIEW

**Comment by dlukanin** [comment]
Hello! Any updates?

**Comment by havsar** [comment]
Hi @dlukanin 

Testing and merging this PR today, latest tomorrow.

Br

**Comment by havsar** [comment]
Will be available by node-ts-cache@3.1.0

**Comment by havsar** [comment]
Available now by https://github.com/havsar/node-ts-cache/tree/v3.2.0

**Pull request merged**
