### PR TITLE
use own folder for build, typescript strict mode, node-cache wrapper added

### PR DESCRIPTION
**Pull request by simllll**
Hi, thanks for this great library.
Unfortunately right now I cannot use the verson from npm, due to the reason that also the source files are included and somehow my typescript environment complains about wrong redis types.
It can be easily solved by moving te output files to a seperate dist folder, and just pack this one for npm. This PR is tested and works already for us :) Just check it out, just let me know if you want me to change something!

Thanks

### CODE REVIEW

**Comment by havsar** [comment]
Hi @simllll 

Thanks for the contribution!
When I only pack the js files for npm all typing information will be lost since the ts files are not there right? Or am I missing something?

Maybe one option would be to generate definition files automcatically (https://www.typescriptlang.org/docs/handbook/compiler-options.html) with tsc command option --declaration.

Any suggestions?

Br

**Comment by simllll** [comment]
Yeah right, sorry I missed that.
"declaration": true in tsconfig should do the trick.

Should I look into it?

**Comment by havsar** [comment]
I will have a look on that and merge it today/tomorrow after some testing.
Br

**Comment by simllll** [comment]
It's not part of the latest release or?
Still getting:
```

../../node_modules/node-ts-cache/src/storage/redis.storage.ts(19,34): error TS2722: Cannot invoke an object which is possibly 'undefined'.
../../node_modules/node-ts-cache/src/storage/redis.storage.ts(32,20): error TS2722: Cannot invoke an object which is possibly 'undefined'.
../../node_modules/node-ts-cache/src/storage/redis.storage.ts(34,16): error TS2722: Cannot invoke an object which is possibly 'undefined'.
../../node_modules/node-ts-cache/src/storage/redis.storage.ts(38,16): error TS2722: Cannot invoke an object which is possibly 'undefined'.
../../node_modules/node-ts-cache/src/strategy/caching/expiration.strategy.ts(27,45): error TS2345: Argument of type 'undefined' is not assignable to parameter of type 'ICacheEntry'.
../../node_modules/node-ts-cache/src/strategy/caching/expiration.strategy.ts(28,13): error TS2322: Type 'undefined' is not assignable to type 'T'.
../../node_modules/node-ts-cache/src/strategy/caching/expiration.strategy.ts(40,22): error TS2532: Object is possibly 'undefined'.
../../node_modules/node-ts-cache/src/strategy/caching/expiration.strategy.ts(62,41): error TS2345: Argument of type 'undefined' is not assignable to parameter of type 'ICacheEntry'.

```

**Comment by havsar** [comment]
No, this ticket is not part of the latest release. I'm working in this ticket today :)

Br

**Comment by einnjo** [comment]
Hi, I'm also getting errors on latest release due to the source files being present in the package.
image

**Comment by morley92** [comment]
Hi @havsar is there any update on merging this?

**Comment by simllll** [comment]
@havsar I have updated my code, hope you like it. Added some stuff / What I did:
* enabled typescript strict mode
* fixed tsconfig for tests
* changed redis to ioredis and fixed tests, also moved deps to peerdependencies
* added a node-cache storage wrapper

let me know what you think. 

Thanks
Simon

**Comment by simllll** [comment]
too many change sin my repo already, I'm merging my branch now into my master. therefore closing this.

**Pull request closed without merging**
