### PR TITLE
move typings to devDependencies

### PR DESCRIPTION
**Pull request by JonathanMeyer2600**
typings of deps shouldn't be exported

### CODE REVIEW

**Comment by havsar** [comment]
@JonathanMeyer2600 Thanks for the PR. Typings for this project were not put into devDependencies on purpose. This project is put with .ts files on the npm registry, it contains the source instead of .d.ts definition files. Back then, Typescript compiler also checked third party libs, maybe this has changed. I will check it.

**Comment by havsar** [comment]
Further reading: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies

**Comment by havsar** [comment]
@JonathanMeyer2600 I just published version 1.2.0 with locked package versions, this will probably fix your issue. Can you try this? If it doesn't work can you please provide a fiddle to reproduce the problem? Thanks.

**Comment by JonathanMeyer2600** [comment]
@havsar here is a quick demo repo: https://github.com/JonathanMeyer2600/node-ts-cache-test
If you run npm run build @types/jest conflict with the types from mocha. Hope this helps.

**Comment by havsar** [comment]
@JonathanMeyer2600 I will check the demo asap. Thanks!

**Comment by JonathanMeyer2600** [comment]
Thanks for looking into this. 
`"compilerOptions": { "skipLibCheck": true }` helped! 
I close the pull request now.

**Pull request closed without merging**
